# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
sass_dir:     ./_sass
collections:  null

name: "Realise"
description: "This is the Realise PoC"

url: "http://localhost:4000"

markdown: rdiscount
permalink: pretty
pygments: true