# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes

title: "A default title: Realise"
description: "A default description: Realise is a digital agency based in Edinburgh."

excerpt_separator: <!--more-->

#url: "http://localhost:4000"
url: "http://craighamnett.github.io"

permalink: pretty
markdown: rdiscount
highlighter: pygments

sass:
    sass_dir: ./_sass
    style: expanded


navigation:
-   text: Home
    title: Go back home
    url: /
    class: nav-home
-   text: Work
    title: See our work
    url: /
    class: nav-work
-   text: Services
    title: What we offer
    url: /about/
    class: nav-services
-   text: Careers
    title: Join the gang
    url: /careers/
    class: nav-careers
-   text: Blog
    title: Read our gossip
    url: /blog/
    class: nav-blog
-   text: Get in touch
    title: Let's talk
    url: /contact-us/
    class: nav-contact